from wx.lib.embeddedimage import PyEmbeddedImage

icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBj"
    "SFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEUAu1UAAACZ"
    "mZn///+qqqpWPjeWAAAAAWJLR0QDEQxM8gAAAEVJREFUCNdFzNsNwDAIQ9HrZgGzSaRMkP2X"
    "ailE8QcciQd8cRZkqeEC4skWGUrUKM5OWG7UzYVjLNYP5mBeyPtAtaN+9wLaTQQ7ufnEVQAA"
    "ACV0RVh0ZGF0ZTpjcmVhdGUAMjAxNS0wNS0xN1QxMDoxNjo0OSswMjowMJ9h29AAAAAldEVY"
    "dGRhdGU6bW9kaWZ5ADIwMTUtMDUtMTdUMTA6MTY6MTQrMDI6MDDHCwzIAAAAAElFTkSuQmCC")
geticonBitmap = icon.GetBitmap
